# Core Metrics Plus - AI Development Configuration
# 
# SUDOLANG VERSION: 1.0.0
# PURPOSE: AI-assisted development configuration
# DOCS: https://github.com/paralleldrive/sudolang-llm-support/blob/main/sudolang.sudo.md
#
# This file follows the Sudolang specification for LLM support.
# Sudolang helps Large Language Models (LLMs) understand:
# 1. Project structure and conventions
# 2. Development workflows and standards
# 3. Testing and quality requirements
# 4. Documentation requirements
#
# AI CAPABILITIES REQUIRED:
# - Code generation
# - Documentation writing
# - Testing suggestions
# - Performance optimization
# - WordPress best practices

metadata:
  version: "1.0.0"
  plugin_name: "Core Metrics Plus"
  description: "WordPress performance optimization plugin"
  repository: "https://github.com/carmelyne/core-metrics-plus"
  ai_compatibility:
    - "Codeium"
    - "GitHub Copilot"
    - "ChatGPT"
  primary_goals:
    - "Optimize WordPress Core Web Vitals"
    - "Improve page load performance"
    - "Maintain theme compatibility"
  context_requirements:
    - "WordPress plugin development experience"
    - "Performance optimization knowledge"
    - "PHP 8.0+ compatibility"

# Development Workflow Configuration
development_workflow:
  feature_development:
    steps:
      1_user_story:
        description: "Create user story in Gherkin format"
        location: "docs/USER_STORIES.md"
        template: |
          Feature: ${feature_name}
            As a ${user_type}
            I want ${desired_action}
            So that ${business_value}

            Scenario: ${scenario_name}
              Given ${precondition}
              When ${action}
              Then ${expected_result}
              And ${additional_outcome}

      2_branch_creation:
        description: "Create feature branch"
        command: "git checkout -b feat/${feature_name}"

      3_documentation_first:
        description: "Update documentation with planned changes"
        files:
          - "docs/PERFORMANCE.md"
          - "README.md"
          - "docs/USER_STORIES.md"

      4_implementation:
        description: "Implement the feature"
        guidelines:
          - "Follow WordPress coding standards"
          - "Add PHPDoc comments"
          - "Include inline documentation"
          - "Consider performance impact"

      5_testing:
        description: "Add and run tests"
        types:
          - "Syntax validation"
          - "Performance benchmarks"
          - "Cross-theme compatibility"
          - "WordPress version compatibility"

      6_pr_creation:
        description: "Create pull request"
        command: "gh pr create"
        requirements:
          - "User story referenced"
          - "Documentation updated"
          - "Tests added"
          - "Performance impact documented"

  commit_workflow:
    conventional_commits: true
    steps:
      - "Add feature files: git add ${files}"
      - "Commit with type: git commit -m '${type}: ${message}'"
      - "Push to remote: git push origin ${branch}"

  review_workflow:
    requirements:
      - "Code follows WordPress standards"
      - "Documentation is updated"
      - "Tests are passing"
      - "Performance is not degraded"
      - "User story is satisfied"

  release_workflow:
    versioning:
      major: "Breaking changes"
      minor: "New features"
      patch: "Bug fixes"
    steps:
      - "Update version numbers"
      - "Update changelog"
      - "Create release tag"
      - "Deploy to WordPress.org"

version_control:
  branch_naming:
    feature: "feat/*"
    bugfix: "fix/*"
    documentation: "docs/*"
    testing: "test/*"
    ci: "ci/*"

  commit_messages:
    # Using Conventional Commits - https://www.conventionalcommits.org/
    feat: "New features"
    fix: "Bug fixes"
    docs: "Documentation changes"
    style: "Code style changes"
    refactor: "Code refactoring"
    test: "Test changes"
    ci: "CI/CD changes"
    chore: "Other changes"

  pr_workflow:
    create_branch:
      command: "git checkout -b ${branch_type}/${branch_name}"
      example: "git checkout -b feat/new-feature"

    make_changes:
      commit_format: "${type}: ${description}\n\n${details}"
      example: |
        feat: add new optimization feature
        
        - Add feature X
        - Update docs
        - Add tests

    create_pr:
      command: "gh pr create --title '${commit_type}: ${description}' --body '${pr_body}'"
      template: |
        ## Changes
        ${bullet_points}

        ## Testing
        - [ ] Tests added/updated
        - [ ] Documentation updated
        - [ ] No breaking changes

    review_process:
      checks:
        - "GitHub Actions workflow passes"
        - "Code review approved"
        - "Documentation updated"

# Plugin Version Management
versioning:
  format: "MAJOR.MINOR.PATCH"
  rules:
    MAJOR: "Breaking changes"
    MINOR: "New features (feat:)"
    PATCH: "Bug fixes (fix:)"

# Testing Requirements
testing:
  environments:
    - "PHP 8.0"
    - "PHP 8.1"
    - "WordPress latest"
    - "WordPress 6.2"
  
  types:
    - "Syntax validation"
    - "Basic smoke tests"
    - "File integrity checks"

# Documentation Structure
documentation:
  required_files:
    - "README.md"
    - "docs/PERFORMANCE.md"
    - "docs/USER_STORIES.md"
  
  code_comments:
    style: "PHPDoc"
    required_sections:
      - "@package"
      - "@since"
      - "@param (if applicable)"
      - "@return (if applicable)"

# Required Files Check
function_check_required_files:
  required_files:
    - "docs/AI_ASSIST.md"
    - "core-metrics-plus.php"
    - "docs/CHANGELOG.md"

# AI Development Notes
ai_notes:
  performance_optimization:
    critical_css:
      approach: "Exclude admin styles only"
      reason: "More reliable than complex critical path analysis"
    
    script_loading:
      approach: "Conservative async loading"
      reason: "Preserve core WordPress functionality"

  code_generation:
    style: "WordPress coding standards"
    patterns: "Use singleton for optimization classes"
    
  testing_focus:
    - "Cross-theme compatibility"
    - "Core Web Vitals impact"
    - "WordPress version compatibility"

# Versioning Workflow
versioning_workflow:
  scheme: "semantic"
  format: "MAJOR.MINOR.PATCH"
  current_version: "1.1.7"
  files_to_update:
    - "core-metrics-plus.php"
    - "readme.txt"
    - "package.json"
    - "composer.json"
  
  increment_rules:
    major:
      - "Breaking changes to public API"
      - "Removal of deprecated features"
      - "Major WordPress version compatibility changes"
    minor:
      - "New features (feat:)"
      - "Non-breaking enhancements"
      - "New optimization capabilities"
    patch:
      - "Bug fixes (fix:)"
      - "Performance improvements"
      - "Documentation updates"
  
  changelog_management:
    location: "CHANGELOG.md"
    sections:
      - "Added"
      - "Changed"
      - "Deprecated"
      - "Removed"
      - "Fixed"
      - "Security"
    commit_to_section_mapping:
      "feat": "Added"
      "fix": "Fixed"
      "docs": "Changed"
      "perf": "Changed"
      "security": "Security"
      "breaking": "Changed"
  
  release_process:
    pre_release:
      - "Update version numbers in all files"
      - "Update changelog"
      - "Run full test suite"
      - "Update readme.txt stable tag"
      - "Create GitHub release draft"
    
    wordpress_org:
      svn_repository: "https://plugins.svn.wordpress.org/core-metrics-plus"
      assets:
        - "assets/banner-772x250.png"
        - "assets/icon-256x256.png"
      required_files:
        - "readme.txt"
        - "core-metrics-plus.php"
        - "includes/*"
        - "assets/*"
    
    post_release:
      - "Tag release on GitHub"
      - "Update WordPress.org repository"
      - "Close related GitHub issues"
      - "Update documentation with new version"
  
  hotfix_workflow:
    branch_naming: "hotfix/${version}"
    requirements:
      - "Critical bug fixes only"
      - "Minimal changes"
      - "Full test coverage"
    process:
      - "Branch from main/master"
      - "Fix critical issue"
      - "Update patch version"
      - "Merge to main and develop"
  
  version_compatibility:
    wordpress:
      minimum: "6.0"
      tested_up_to: "6.4"
      requires_php: "8.0"
    check_compatibility:
      - "PHP versions"
      - "WordPress core"
      - "Popular themes"
      - "Common plugins"
