name: WordPress Plugin CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        php-versions: ['7.4', '8.0', '8.1']
        wordpress-versions: ['latest', '6.2', '6.1']

    name: WP ${{ matrix.wordpress-versions }} on PHP ${{ matrix.php-versions }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, xml
          coverage: none
          tools: composer:v2

      - name: Check PHP syntax
        run: |
          find . -type f -name '*.php' -print0 | xargs -0 -n1 php -l

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress

      - name: Check WordPress Coding Standards
        run: |
          composer global require wp-coding-standards/wpcs
          phpcs --standard=WordPress ./includes/

      - name: Basic smoke test
        run: |
          # Check if critical files exist
          test -f includes/critical-css.php
          test -f includes/script-optimizer.php
          
          # Check file permissions
          test -r includes/critical-css.php
          test -r includes/script-optimizer.php
          
          # Validate PHP files
          php includes/critical-css.php
          php includes/script-optimizer.php

      - name: Archive code coverage results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: clover.xml
